
services:
  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Muhammet.evkaya.1
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_volume:/var/opt/mssql
  microservice1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
  microservice2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:8080"