
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
  microservice1.api:
    image: ahmetfarukevkaya/microservice1:${version}
    container_name: microservice1-container
    build:
      context: .
      dockerfile: MicroService1.API/Dockerfile
  microservice2.api:
    image: ahmetfarukevkaya/microservice2:${version}
    container_name: microservice2-container
    build:
      context: .
      dockerfile: MicroService2.API/Dockerfile
volumes:
  sqlserver_volume: